- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: help wanted
  color: 008672
  description: Extra attention is needed
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: question
  color: d876e3
  description: Further information is requested
- name: stale
  color: cfd3d7
  description: Marked as stale due to inactivity
- name: security
  color: b60205
  description: Security-related issue
