# Markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Configure line length with exceptions
MD013:
  line_length: 120
  code_blocks: false
  tables: false
  headings: false

# Disable some rules that are too strict for documentation
MD033: false # Allow inline HTML (useful for badges and formatting)
MD041: false # First line in file should be a top level header (README starts with title)

# Configure specific rules
MD003:
  style: "atx" # Use # style headers, not === underline style

MD004:
  style: "dash" # Use - for unordered lists

MD007:
  indent: 2 # Unordered list indentation (2 spaces)

MD012:
  maximum: 2 # Allow up to 2 consecutive blank lines

MD029:
  style: "ordered" # Use 1. 2. 3. for ordered lists

MD035:
  style: "---" # Use --- for horizontal rules
