---
labels: ["idea"]
body:
  - type: markdown
    attributes:
      value: |
        # Share Your Idea

        Got an idea for the User Management Service? Share it here! This is a place for brainstorming
        and discussing potential features, improvements, or changes.

  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: Describe your idea
      placeholder: What's your idea?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem It Solves
      description: What problem does this idea address?
      placeholder: What problem would this solve?

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this idea?
      placeholder: How would this help users?

  - type: textarea
    id: considerations
    attributes:
      label: Considerations
      description: Any challenges or considerations?
      placeholder: What should we think about?
