---
labels: ["show-and-tell"]
body:
  - type: markdown
    attributes:
      value: |
        # Show and Tell

        Built something cool with the User Management Service? Share it with the community!

  - type: textarea
    id: project
    attributes:
      label: What Did You Build?
      description: Describe what you built
      placeholder: Tell us about your project
    validations:
      required: true

  - type: textarea
    id: how
    attributes:
      label: How You Used This Service
      description: How did you integrate or use this service?
      placeholder: Describe your implementation
    validations:
      required: true

  - type: textarea
    id: challenges
    attributes:
      label: Challenges & Solutions
      description: What challenges did you face and how did you solve them?
      placeholder: Share your experience

  - type: textarea
    id: links
    attributes:
      label: Links
      description: Links to your project (if public)
      placeholder: |
        - GitHub: https://...
        - Demo: https://...

  - type: textarea
    id: tips
    attributes:
      label: Tips for Others
      description: Any tips for others who want to build something similar?
      placeholder: Share your wisdom!
