---
# k8s/pod-disruption-budget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: user-management-pdb
  namespace: user-management
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: user-management
