name: Documentation Issue
description: Report missing or incorrect documentation
title: "[Docs]: "
labels: ["documentation"]
assignees:
  - jsamuelsen11
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Missing info
        - Incorrect info
        - Typo
        - Unclear / Confusing
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is wrong with the documentation?
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location (File/URL)
      placeholder: README.md
