name: Security Vulnerability (Low Severity)
description: Report a low-severity security issue or concern
title: "[Security]: "
labels: ["security"]
assignees:
  - jsamuelsen11
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** For Critical or High severity issues, do NOT use this form. Please use [GitHub Security Advisories](https://github.com/Recipe-Web-App/user-management-service/security/advisories/new).
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Information Only
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security issue or concern.
    validations:
      required: true
