---
name: Security Vulnerability (Low Severity)
description: Report a low-severity security concern (use Security Advisories for critical issues)
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees:
  - jsamuelsen11
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** For critical security vulnerabilities, please use
        [GitHub Security Advisories](https://github.com/Recipe-Web-App/user-management-service/security/advisories/new)
        to report privately.

        This template is for **low-severity** security concerns that can be discussed publicly.

  - type: checkboxes
    id: confirm_severity
    attributes:
      label: Severity Confirmation
      description: Please confirm this is a low-severity issue
      options:
        - label: I confirm this is a LOW severity security concern (not exploitable, best practice, or informational)
          required: true
        - label: I have NOT found a critical, high, or medium severity vulnerability
          required: true

  - type: textarea
    id: description
    attributes:
      label: Security Concern Description
      description: Describe the security concern
      placeholder: What is the security concern?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of security concern is this?
      options:
        - Security Headers Missing
        - Verbose Error Messages
        - Information Disclosure (minimal)
        - Security Best Practice
        - Dependency Security Advisory
        - Configuration Hardening
        - Code Quality/Security
        - Documentation/Security Guidance
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker potentially achieve? (should be minimal for low severity)
      placeholder: Describe the potential impact
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Observe
      description: How can this concern be observed?
      placeholder: |
        1. Check...
        2. Observe...
    validations:
      required: true

  - type: textarea
    id: recommendation
    attributes:
      label: Recommendation
      description: How do you recommend fixing this?
      placeholder: Describe your recommendation

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant security resources, CVEs, or documentation
      placeholder: |
        - https://...
        - CVE-...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have confirmed this is LOW severity
          required: true
        - label: I understand critical/high/medium issues should use Security Advisories
          required: true
        - label: I have redacted any sensitive information
          required: true
