### Social Features Tests

### Get Following List - Default Pagination
GET http://user-management.local/api/v1/user-management/following
Authorization: Bearer {{accessToken}}

###

### Get Following List - Custom Pagination
GET http://user-management.local/api/v1/user-management/following?limit=10&offset=5
Authorization: Bearer {{accessToken}}

###

### Get Following List - Count Only
GET http://user-management.local/api/v1/user-management/following?count_only=true
Authorization: Bearer {{accessToken}}

###

### Get Followers List - Default Pagination
GET http://user-management.local/api/v1/user-management/users/123e4567-e89b-12d3-a456-426614174000/followers
Authorization: Bearer {{accessToken}}

###

### Get Followers List - Custom Pagination
GET http://user-management.local/api/v1/user-management/users/123e4567-e89b-12d3-a456-426614174000/followers?limit=15&offset=10
Authorization: Bearer {{accessToken}}

###

### Get Followers List - Count Only
GET http://user-management.local/api/v1/user-management/users/123e4567-e89b-12d3-a456-426614174000/followers?count_only=true
Authorization: Bearer {{accessToken}}

###

### Follow User
POST http://user-management.local/api/v1/user-management/users/123e4567-e89b-12d3-a456-426614174000/follow/456e7890-e89b-12d3-a456-426614174001
Authorization: Bearer {{accessToken}}

###

### Unfollow User
DELETE http://user-management.local/api/v1/user-management/users/123e4567-e89b-12d3-a456-426614174000/follow/456e7890-e89b-12d3-a456-426614174001
Authorization: Bearer {{accessToken}}

###

### Get User Activity - Default Limit
GET http://user-management.local/api/v1/user-management/users/123e4567-e89b-12d3-a456-426614174000/activity?per_type_limit=5
Authorization: Bearer {{accessToken}}

###
